#!/bin/bash

# Select the application database
mongo --eval 'use goiodi;'

# Remove everything (all collections documents) in the database
mongo --eval 'db.dropDatabase();'

# Make some fields unique
mongo --eval 'db.users.ensureIndex({username:1},{unique:true});'
mongo --eval 'db.users.ensureIndex({email:1},{unique:true});'

mongo --eval 'db.words.ensureIndex({word:1},{unique:true});'
